language: java
os:
  - windows
jdk:
  - openjdk9

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script move to :
  - cd ../../src

script:

  - mvn clean verify -P test-consumer,test-business
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
  - cd ../../src